plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev'
}

dependencies {
    implementation "net.neoforged:neoforge:26.1.2.76"
    implementation project(':common')
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}

jar {
    from project(':common').sourceSets.main.output
}
