plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev'
}

dependencies {
    implementation "net.neoforged:neoforge:21.1.65"
    implementation project(':common')
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

jar {
    from project(':common').sourceSets.main.output
}
